# Generated by Django 5.2.5 on 2025-08-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_desc_contact_message_remove_contact_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Grievance',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
